import { useQuery } from "@apollo/client";
import Head from "next/head";
import { useRouter } from "next/router";
import { LikeableInfo } from "../../src/components/LikeableInfo";
import { LikeDislikeActions } from "../../src/components/LikeDislikeActions";
import { VoteableInfo } from "../../src/components/VoteableInfo";
import { VoteActions } from "../../src/components/VoteActions";
import { graphql } from "../../__generated__/gql";

const GetProductDocument = graphql(`
  query GetProduct($id: ID!) {
    product(id: $id) {
      id
      name
      ...LikeableInfo_Likeable
      ...LikeDislikeActions_Likeable
      ...VoteableInfo_Voteable
      ...VoteActions_Voteable
    }
  }
`);

export default function Product() {
  const { query } = useRouter();
  const { data, loading, error } = useQuery(GetProductDocument, {
    variables: {
      id: decodeURIComponent((query?.id as string) || ""),
    },
  });

  if (!data?.product) return null;

  return (
    <div>
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Product: {data.product.name}</h1>
        <hr />
        <LikeableInfo likeable={data.product} />
        <LikeDislikeActions likeable={data.product} />
        <hr />
        <VoteableInfo voteable={data.product} />
        <VoteActions voteable={data.product} />
      </main>
    </div>
  );
}
